# Generated by Django 3.2 on 2023-03-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
