# Generated by Django 3.2 on 2023-04-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
