# Generated by Django 3.2 on 2023-04-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
