# Generated by Django 3.2 on 2023-04-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
