# Generated by Django 3.2 on 2023-04-19 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20230330_0606'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='neighborhood.neighborhood'),
            preserve_default=False,
        ),
    ]
