# Generated by Django 3.2 on 2023-04-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_listing_price'),
        ('marketplace', '0002_auto_20230424_1916'),
    ]

    operations = [
    ]
