# -*- coding: utf-8 -*-
"""bam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q7rEtBDEcvzaVS-TTsWxmpIffORDgoG0
"""

import pandas as pd
import json

dataURL = 'https://raw.githubusercontent.com/gcivil-nyu-org/INET-Monday-Spring2023-Team-5/nyc-opendata-playground/scripts/datasets/neighborhoods.csv'
data = pd.read_csv(dataURL, index_col=0)

# Convert the dataframe to a list of dictionaries, with each dictionary representing a row
rows = data.to_dict("records")

# Convert each dictionary to a fixture object and add it to a list of fixtures
fixtures = []
for i, row in enumerate(rows):
    fixture = {
        "model": "neighborhood.neighborhood",
        "pk": i + 1,
        "fields": {
            "name": row["name"],
            "borough": row["borough"],
            "description": row["description"],
            "lat": float(row["lat"]),
            "lon": float(row["lon"]),
        }
    }
    fixtures.append(fixture)

# Write the list of fixtures to a JSON file
with open("../fixtures/neighborhood.json", "w") as f:
    json.dump(fixtures, f, indent = 2)
