# Generated by Django 3.2 on 2023-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_delete_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='borough',
            field=models.CharField(default='xxx', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default='xxx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
