# Generated by Django 3.2 on 2023-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20230330_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='crimes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
