# Generated by Django 3.2 on 2023-05-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_auto_20230501_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='crimes',
            new_name='crime_count',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='noise_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
